config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create_with_github', via: [:get, :post]
  resources :pokemons, only: [:show, :index] 
  resources :movies, only: [:show, :index]
  resources :users, only: [:show, :new, :create] do #show user's homepage; link to every team(if any)
    resources :teams 
  end 
  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/mypokemons', to: 'pokemons#mypokemons'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#new
#create
#edit
#update
#show
#index
#delete

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
    layout "welcome"
    def home 
    end
    def new 
        render :"/users/new"
    end

    def create 
        user = User.find_by_name(params[:user][:name])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else 
            @errors = ["This username and password combination cannot be found."]
            render :"/users/new"
        end
    end
    def destroy 
        session.clear 
        redirect_to root_path
    end

    def create_with_github
        user = User.find_or_create_by(name: github_name) do |u|
            u.password = 'ThisIsADummyPasswordThatBcrpytNeedsSoThatTheUserWillSave'
            u.image = github_image
            u.save
        end
        if user
            session[:user_id] = user.id
            redirect_to user_path(current_user)
        else 
            redirect_to root_path
        end 
    end

    private 
    def github_name
        request.env['omniauth.auth']['info']['name']
    end
    def github_image 
        request.env['omniauth.auth']['info']['image']
    end
end

app/views/session/home.html.erb
<br><br>
<div class="home-pics">
<img src="/assets/pika.png" class="in-line">
<img src="/assets/eevee.png" class="in-line">
<img src="/assets/bulb.png" class="in-line">
<img src="/assets/char.png" class="in-line">
<img src="/assets/jig.png" class="in-line">
</div>
<div class="home">
<a href="<%=login_path%>">
<button type="button" value="Continue My Pokemon Journey" class="front-button">
    Continue My Pokemon Journey
</button></a>
<br><br>
<a href="<%=new_user_path%>">
<button type="button" value="Start My Pokemon Journey" class="front-button">
    Start My Pokemon Journey
</button></a><br><br>
<%= button_to 'Signing in with the GitHub strategy', '/auth/github', class:'front-button'%>
</div><br><br>
<div style="width:300px; margin:auto; position:relative;">
<audio controls autoplay preload loop=true src="/assets/poke1.mp3">
</audio>
</div>
<br><br>

<style>
.home-pics {
    margin-left: auto;
    margin-right: auto;
    text-align: center;
    display: block;
}

.in-line {
    width: 150px;
}

.in-line:hover {
    transform: scale(1.1);
}

.home {
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    width:900px;
    padding: 22px 26px;
    border: 7px solid #c4d7ff;
    border-radius: 55px;
    box-shadow: 8px 8px 10px 2px #b3b3b3; 
    background: rgba(99, 140, 222);
    background: rgba(99, 140, 222, 0.22);
}

.front-button {
    padding: 22px 26px;
    border-radius: 15px;
    transition-duration: 0.4s;
    background-color: white;
    font-size: 30px;
    letter-spacing: 3px;
    color: rgba(189, 198, 239, 1);
    font-family: "PokemonSolid";
    box-shadow: 1px 1px 3px 2px rgba(168, 183, 215, 1);
    border: 2px solid #d1ceed;
}

.front-button:hover {
  background-color: rgba(189, 198, 239, 1);
  /* -webkit-text-stroke: 1.3px rgba(144, 162, 249, 1); */
  color: white;
  transform: scale(1.1);
}

.front-button:active {
  transform: translateY(4px);
}


</style>