config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create_with_github', via: [:get, :post]
  resources :pokemons, only: [:show, :index] 
  resources :movies, only: [:show, :index]
  resources :users, only: [:show, :new, :create] do #show user's homepage; link to every team(if any)
    resources :teams 
  end 
  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/mypokemons', to: 'pokemons#mypokemons'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#new
#create
#edit
#update
#show
#index
#delete

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :pokemons_teams  
    has_many :teams, through: :pokemons_teams 
    scope(:type_search, ->(query) { self.where("types LIKE ?", "%#{query}%")})
    scope(:name_search, ->(query) { self.where("name LIKE ?", "%#{query}%")})
    scope(:number_search, ->(query) { self.where("pokedex_number LIKE ?", "%#{query}%")})

    
    def check_abilities 
        if self.abilities.include?("[")
            self.abilities = self.abilities.split(",").collect{|a| a.gsub!(/\W+/, ' ').strip}.join(", ")
        end
        self.abilities
    end

    # def self.all_types 
    #     array = []
    #     self.all.each do |p|
    #         if p.types.include?(",")
    #             p.types.split(",").each do |a|
    #                 array << a.strip unless array.include?('a')
    #             end 
    #         else 
    #             array << p.types unless array.include?(p.types) 

    #         end
    #     end
    #     array.uniq
    # end

end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
    def index
        @pokemons = Pokemon.all
    end

    def show 
        @pokemon = Pokemon.find_by(id: params[:id])
    end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    layout "main"
    def index
        if params[:searching_for]
            p = params[:searching_for]
            if p == "types"
                @pokemons = Pokemon.type_search(params[:query])
            elsif p == "name"
                @pokemons = Pokemon.name_search(params[:query])
            else 
                @pokemons = Pokemon.number_search(params[:query])
            end 
        else 
            @pokemons = Pokemon.all
        end
    end

    def show 
        @pokemon = Pokemon.find_by(id: params[:id])
    end

    def mypokemons 
        @pokemons = current_user.pokemons 
    end

end

app/views/pokemons/_pokemon.html.erb
<div class="poke-box">
<br><br>
<h1 class="name-header"> <%= pokemon.pokedex_number %> - <%= pokemon.name %> </h1>
<img class="poke-pic" src="<%=pokemon.image%>">
<p class="description"> <%= pokemon.description %> </p> <br><br>
<p class="poke-info"> Height: <%= pokemon.height %> </p>
<p class="poke-info"> Weight: <%= pokemon.weight %> </p>
<p class="poke-info"> Type: <%= pokemon.types %> </p> 
<p class="poke-info"> Weakness: <%= pokemon.weaknesses %> </p>

<p class="poke-info"> Ability: <%= pokemon.check_abilities %> </p>
<br><br>
</div>
<br><br><br>

app/views/pokemons/index.html.erb
<div class="search-bar">
<%= form_tag("/pokemons", :method => "get") do %>
<span class="text-search">
Search by
</span>
<span class="text-search">
<select name="searching_for" id="searching_for" class="searching_for">
  <option value="types">Type</option>
  <option value="pokedex_number">Pokédex Number</option>
  <option value="name">Name</option>
</select> 
<%# Type:  %>
</span>
<%= text_field_tag :query, "", class: "search" %>
<span class="search-padding"></span>
<button class="search-button">Search</button>
<% end %>
</div>
<br><br>

<div class="display-box">
<% @pokemons.each do |p| %>
<div class="container">
 <a href="<%=pokemon_path(p)%>" class="poke-link"> <img src="<%=p.image%>" class="image">
    <div class="overlay"><%=p.name%></div> </a>
</div>
<% end %>
</div>

<style>


.searching_for {
  font-family: "Cafe";
  color: #ff7d7d;
  border-radius: 10px;
  box-shadow: 1px 1px 4px #ffb0b0;
  border: 1px solid #ff7d7d;
  height: 28.2px;
}

.text-search {
  padding-right: 8px;
  font-family: "Cafe";
  font-size: 18px;
  color: #ff7d7d;

}

.search-padding {
  padding-left: 10px;
}

.search {
  border-radius: 10px;
  width: 200px;
  box-shadow: 1px 1px 4px #ffb0b0;
  border: 1px solid #ff7d7d;
  color: #2777cc;
  font-family: "Cafe";
}

.search-button {
  border-radius: 10px;
  font-family: "Cafe";
  background-color: white;
  border: 1px solid #ff7d7d;
  padding-left: 9px;
  padding-right: 9px;
  padding-top: 3px;
  padding-bottom: 3px;
  box-shadow: 1px 1px 4px #ffb0b0; 
  color: #ff7d7d;
}

.search-button:active {
  transform: translateY(4px);
}

.search-button:hover {
  background-color: #ff7d7d;
  color: white;
}

@font-face {
  font-family: 'PokemonSolid';
  src: url('/assets/PokemonSolid.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

* {box-sizing: border-box}

.search-bar {
  text-align: center;
}

.display-box {
  display: grid;
  grid-template-columns: auto auto auto auto auto auto;
  row-gap: 30px;
  column-gap: 10px;
  justify-content:center;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}


.image {
  display: block;
  width: 280px;
  height: auto;
  box-shadow: 3px 4px 9px 7px #f7faff;
  border-radius: 55px;
}

.poke-link {
  text-decoration: none;
}

.container {
  box-sizing: border-box;
}

.overlay {
  position: relative;
  /* top: 5%; */
  width: 100%;
  transition: .5s ease;
  opacity:0;
  color: white;
  -webkit-text-stroke: 2px #578cff;
  font-size: 30px;
  padding-top: 15px;
  text-align: center;
  letter-spacing: 3px;
  font-family: "PokemonSolid";
  /* border-radius: 55px; */
}

.container:hover .overlay {
  opacity: 1;
  transform: scale(1.07);
  transition: 0.5s ease-in-out;
}

.container:hover .image {
  opacity: 1;
  transform: scale(1.07);
  transition: 0.5s ease-in-out;

}

</style>

app/views/pokemons/mypokemons.html.erb
<%# render partial: 'index' %>

<div class="display-box">
<% @pokemons.each do |p| %>
<div class="container">
 <a href="<%=pokemon_path(p)%>" class="poke-link"> <img src="<%=p.image%>" class="image">
    <div class="overlay"><%=p.name%></div> </a>
</div>
<% end %>
</div>

<style>


.searching_for {
  font-family: "Cafe";
  color: #ff7d7d;
  border-radius: 10px;
  box-shadow: 1px 1px 4px #ffb0b0;
  border: 1px solid #ff7d7d;
  height: 28.2px;
}

.text-search {
  padding-right: 8px;
  font-family: "Cafe";
  font-size: 18px;
  color: #ff7d7d;

}

.search-padding {
  padding-left: 10px;
}

.search {
  border-radius: 10px;
  width: 200px;
  box-shadow: 1px 1px 4px #ffb0b0;
  border: 1px solid #ff7d7d;
  color: #2777cc;
  font-family: "Cafe";
}

.search-button {
  border-radius: 10px;
  font-family: "Cafe";
  background-color: white;
  border: 1px solid #ff7d7d;
  padding-left: 9px;
  padding-right: 9px;
  padding-top: 3px;
  padding-bottom: 3px;
  box-shadow: 1px 1px 4px #ffb0b0; 
  color: #ff7d7d;
}

.search-button:active {
  transform: translateY(4px);
}

.search-button:hover {
  background-color: #ff7d7d;
  color: white;
}

@font-face {
  font-family: 'PokemonSolid';
  src: url('/assets/PokemonSolid.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

* {box-sizing: border-box}

.search-bar {
  text-align: center;
}

.display-box {
  display: grid;
  grid-template-columns: auto auto auto auto auto auto;
  row-gap: 30px;
  column-gap: 10px;
  justify-content:center;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}


.image {
  display: block;
  width: 280px;
  height: auto;
  box-shadow: 3px 4px 9px 7px #f7faff;
  border-radius: 55px;
}

.poke-link {
  text-decoration: none;
}

.container {
  box-sizing: border-box;
}

.overlay {
  position: relative;
  /* top: 5%; */
  width: 100%;
  transition: .5s ease;
  opacity:0;
  color: white;
  -webkit-text-stroke: 2px #578cff;
  font-size: 30px;
  padding-top: 15px;
  text-align: center;
  letter-spacing: 3px;
  font-family: "PokemonSolid";
  /* border-radius: 55px; */
}

.container:hover .overlay {
  opacity: 1;
  transform: scale(1.07);
  transition: 0.5s ease-in-out;
}

.container:hover .image {
  opacity: 1;
  transform: scale(1.07);
  transition: 0.5s ease-in-out;

}

</style>

app/views/pokemons/show.html.erb
<%= render partial: 'pokemon', locals: {pokemon: @pokemon} %>

<style>

.poke-box {
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    width:900px;
    border: 7px solid #c4d7ff;
    border-radius: 55px;
    box-shadow: 8px 8px 25px 7px #ced5e0; 
    background: rgba(99, 140, 222, 0.22);
}

.poke-box:hover {
    transform: scale(1.05);
    transition: 1s ease-in-out;
}

.name-header {
    font-family: "MilkyNice";
    font-size: 50px;
    text-align: center;
    color: #ffffff;
    -webkit-text-stroke: 1.3px #578cff;
}

.name-header:hover {
    color: #578cff;
}

.poke-pic {
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.poke-info {
    font-family: "MilkyNice";
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    width: 30em;  
    font-size: 25px;
    color: #ffffff;
    -webkit-text-stroke: 1.2px #578cff;
}

.poke-info:hover {
    color: #578cff;
}

.description {
    font-family: "MilkyNice";
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    width: 25em;
    font-size: 30px;
    color: #ffffff;
    -webkit-text-stroke: 1.5px #578cff;
}

.description:hover {
    color: #578cff;
}

</style>