config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create_with_github', via: [:get, :post]
  resources :pokemons, only: [:show, :index] 
  resources :movies, only: [:show, :index]
  resources :users, only: [:show, :new, :create] do #show user's homepage; link to every team(if any)
    resources :teams 
  end 
  root 'sessions#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/mypokemons', to: 'pokemons#mypokemons'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#new
#create
#edit
#update
#show
#index
#delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonFanClubProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<br><br><br>

<div class="title">
<a href="<%=user_path(current_user)%>" class="no-link">
<h1 class="rotate-center">
<img src="/assets/pokeball.gif" class="ball"><span class="right-span"></span>
Pokémon Fan Club
<span class="left-span"></span>
<img src="/assets/pokeball.gif" class="ball">
</h1>
</a>
</div>

<br><br>
<div class="nav1">
<ul class="nav justify-content-center">
  <li class="nav-bar">
    <a class="nav-link" aria-current="page" href="<%= pokemons_path %>">All Pokémon</a>
  </li>
  <li class="nav-bar">
    <a class="nav-link" aria-current="page" href="<%= movies_path %>">Movies</a>
  </li>
  <li class="nav-bar">
    <a class="nav-link" aria-current="page" href="<%= mypokemons_path %>">My Pokémon</a>
  </li>
  <li class="nav-bar">
  <div class="dropdown">
    <a class="nav-link" href="<%=user_teams_path(current_user)%>">My Teams</a>
      <div class="dropdown-content">
        <a class="dropdownlink" href="<%=user_teams_path(current_user)%>">All Teams</a>
        <a class="dropdownlink" href="<%=new_user_team_path(current_user)%>">Create New Team</a>
      </div>
  </div>
  </li>
  <li class="nav-bar">
    <a class="nav-link" href="<%=random_movie_or_pokemon%>">Surprise Me</a>
  </li>
  <li class="nav-bar">
    <a class="nav-link" href="<%=logout_path%>">Log Out</a>
  </li>
</ul>
<br><br>
</div>
<br><br><br>
</head>
<body>

<%= yield %> 


<br><br><br><br>
<div class="footer">
<img src="/assets/snore.png" class="bot">
<img src="/assets/snore.png" class="bot">
<img src="/assets/snore.png" class="bot">
<img src="/assets/snore.png" class="bot">
<img src="/assets/snore.png" class="bot">
</div>

<style>
html {
  cursor: url("/assets/Pokemon.cur"), default;
}
@font-face {
  font-family: 'PokemonHollow';
  src: url('/assets/PokemonHollow.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'PokemonSolid';
  src: url('/assets/PokemonSolid.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'Cafe';
  src: url('/assets/Cafe.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'Chicken';
  src: url('/assets/Chicken.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'MilkyNice';
  src: url('/assets/MilkyNice.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

.right-span {
  padding-right: 13px;
}

.left-span {
  padding-left: 13px;
}

.ball {
  width: 5%;
}

.rotate-center {
  font-family: "PokemonSolid";
  text-align: center;
  letter-spacing: 3px;
  color: #cc3b3b;
  font-size: 70px;
  text-shadow: 5px 5px 8px #949494;
  -webkit-text-stroke: 3px #a10000;
}

@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

.title:hover {
    transform: scale(1.1);
    transition: 0.8s ease-in-out;

}

.no-link {
  text-decoration: none;
}

.nav1 {
    background: rgba(214, 228, 255, 0.56);
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    border: 3px solid #c4d7ff;
    height: 90px;
}

.nav-bar {
    display: block;
    padding: 7px 20px;
}

.nav-link {
  font-family: "PokemonSolid";
  letter-spacing: 3px;
  font-size: 28px;
  -webkit-text-stroke: 1.5px #8fb4ff;
  color: #5886db;
}

.nav-link:hover {
  transform: scale(1.18);
  /* transition: 0.4s ease-in-out; */
  color: #7076ff;
  -webkit-text-stroke: 1.5px #a1a5ff;
}

.nav-link:active {
  color: white;
  -webkit-text-stroke: 1.5px #a1a5ff;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #d4e2ff;
  letter-spacing: 1.2px;
  font-family: "PokemonSolid";
  min-width: 150px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: #788cff;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {
  background-color: #ebf1ff;
  color: #8458db;
  }

.dropdown:hover .dropdown-content {
  display: block;
}


.dropdownlink:hover {
  color: #b52487;
  transform: scale(1.03);
}

.dropdownlink:active {
  color: #503b94;
}

.footer {
  background: rgba(214, 228, 255, 0.56);
  margin-left: auto;
  margin-right: auto;
  text-align: center;
  border: 1px solid #c4d7ff;

}

.bot {
  width: 180px;
  display: inline;
}

</style>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<br><br><br>
<div class="title">
<h1 class="rotate-center">
<img src="/assets/pokeball.gif" class="ball">
<span class="left-span"></span>
Pokémon Fan Club
<span class="left-span"></span>
<img src="/assets/pokeball.gif" class="ball">
</h1>
</div>

<br><br>

<%= yield %> 


<br><br><br><br>
<div class="footer">
<img src="/assets/psy.png" class="bot">
<img src="/assets/psy.png" class="bot">
<img src="/assets/psy.png" class="bot">
<img src="/assets/psy.png" class="bot">
<img src="/assets/psy.png" class="bot">
<img src="/assets/psy.png" class="bot"><br>
</div>

<style>
html {
  cursor: url("/assets/Pokemon.cur"), default;
}
@font-face {
  font-family: 'PokemonHollow';
  src: url('/assets/PokemonHollow.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'PokemonSolid';
  src: url('/assets/PokemonSolid.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'Chicken';
  src: url('/assets/Chicken.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'MilkyNice';
  src: url('/assets/MilkyNice.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

.right-span {
  padding-right: 13px;
}

.left-span {
  padding-left: 13px;
}

.ball {
  width: 5%;
  /* box-shadow: 0px 6px 5px #ccc;
  border-radius:190px; */
}

.rotate-center {
  font-family: "PokemonSolid";
  text-align: center;
  letter-spacing: 3px;
  color: #cc3b3b;
  font-size: 70px;
  text-shadow: 5px 5px 8px #949494;
  -webkit-text-stroke: 3px #a10000;
	/* -webkit-animation: rotate-center 0.6s ease-in-out both; */
	        /* animation: rotate-center 2.6s ease-in-out both; */
}

@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

.title:hover {
    transform: scale(1.1);
    transition: 0.8s ease-in-out;
}
.footer {
  background: #d4e2ff;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}

.bot {
  width: 180px;
  display: inline;
}

</style>

</body>
</html>